### ISSUE TITLE
No valid url specified

### ISSUE THREAD

**Issue by djtecha** [Napal-innovation/Kibana-extractor-plugin#2]
Trying to install and the following happens.

> > **bin/kibana plugin --install Napal-innovation/Kibana-extractor-plugin**
> > Installing Kibana-extractor-plugin
> > Attempting to transfer from https://download.elastic.co/Napal-innovation/Kibana-extractor-plugin/Kibana-extractor-plugin-latest.tar.gz

**Comment by ddavidebor** [comment]
@djtecha you have to specify a full valid url. i've always seen zip used, i don't know if tar.gz will work.

example:
`./bin/kibana-plugin install  https://github.com/fermiumlabs/mathlion/releases/download/version_name/mathlion-major.minor.patch.zip`

**Comment by Napal-innovation** [comment]
Added more explicit readme.md instruction for online install.
